SET SERVEROUTPUT ON;

DECLARE
    ROLE_EXISTS INTEGER;
BEGIN
    -- Check if ICPS_ADMIN_ROLE exists
    SELECT COUNT(*) INTO ROLE_EXISTS FROM DBA_ROLES WHERE ROLE = 'ICPS_ADMIN_ROLE';

    -- Create ICPS_ADMIN_ROLE if it does not exist
    IF ROLE_EXISTS = 0 THEN
        EXECUTE IMMEDIATE 'CREATE ROLE ICPS_ADMIN_ROLE';
        DBMS_OUTPUT.PUT_LINE('Role ICPS_ADMIN_ROLE created');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Role ICPS_ADMIN_ROLE already exists');
    END IF;

    -- Grant permissions to ICPS_ADMIN_ROLE
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON INSURANCE_APPLICATION TO ICPS_ADMIN_ROLE';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON POLICYHOLDER TO ICPS_ADMIN_ROLE';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON AGENT TO ICPS_ADMIN_ROLE';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON PROVIDER TO ICPS_ADMIN_ROLE';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON ADDRESS TO ICPS_ADMIN_ROLE';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON POLICY TO ICPS_ADMIN_ROLE';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON CLAIM TO ICPS_ADMIN_ROLE';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON PAYMENT TO ICPS_ADMIN_ROLE';
    EXECUTE IMMEDIATE 'GRANT ALL PRIVILEGES ON INSURANCE_TYPE TO ICPS_ADMIN_ROLE';

    DBMS_OUTPUT.PUT_LINE('Permissions granted to ICPS_ADMIN_ROLE');
END;
/

-- End of script for ICPS_ADMIN_ROLE creation and permission grant
