SET SERVEROUTPUT ON;

DECLARE
    role_exists INTEGER;
BEGIN
    -- Check if ICPS_CORE_ROLE exists
    SELECT COUNT(*)
    INTO role_exists
    FROM DBA_ROLES
    WHERE ROLE = 'ICPS_CORE_ROLE';

    -- Drop the role if it exists
    IF role_exists = 1 THEN
        EXECUTE IMMEDIATE 'DROP ROLE ICPS_CORE_ROLE';
        DBMS_OUTPUT.PUT_LINE('Role ICPS_CORE_ROLE dropped');
    END IF;

    -- Create ICPS_CORE_ROLE
    EXECUTE IMMEDIATE 'CREATE ROLE ICPS_CORE_ROLE';
    DBMS_OUTPUT.PUT_LINE('Role ICPS_CORE_ROLE created');

    -- Granting table-level privileges to ICPS_CORE_ROLE
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ADDRESS TO ICPS_CORE_ROLE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON INSURANCE_TYPE TO ICPS_CORE_ROLE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON POLICYHOLDER TO ICPS_CORE_ROLE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON PROVIDER TO ICPS_CORE_ROLE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON AGENT TO ICPS_CORE_ROLE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON INSURANCE_APPLICATION TO ICPS_CORE_ROLE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON POLICY TO ICPS_CORE_ROLE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON CLAIM TO ICPS_CORE_ROLE';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON PAYMENT TO ICPS_CORE_ROLE';
    DBMS_OUTPUT.PUT_LINE('Table-level privileges granted to ICPS_CORE_ROLE');

    -- Directly granting restricted privileges to ICPS_CORE user
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO ICPS_CORE';
    DBMS_OUTPUT.PUT_LINE('UNLIMITED TABLESPACE privilege granted to ICPS_CORE');

    -- Assigning ICPS_CORE_ROLE to ICPS_CORE user
    EXECUTE IMMEDIATE 'GRANT ICPS_CORE_ROLE TO ICPS_CORE';
    DBMS_OUTPUT.PUT_LINE('ICPS_CORE_ROLE granted to ICPS_CORE');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Exception occurred: ' || SQLERRM);
END;
/

-- End of script for creating, granting privileges, and assigning ICPS_CORE_ROLE
