SET SERVEROUTPUT ON;

BEGIN
    -- Grant privileges to PROVIDER
    dbms_output.put_line('Granting privileges to PROVIDER...');
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON PROVIDER TO PROVIDER';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON AGENT TO PROVIDER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON POLICYHOLDER TO PROVIDER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON INSURANCE_APPLICATION TO PROVIDER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON POLICY TO PROVIDER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON CLAIM TO PROVIDER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON PAYMENT TO PROVIDER';
    dbms_output.put_line('Privileges granted to PROVIDER.');

    -- Grant privileges to POLICY_HOLDER
    dbms_output.put_line('Granting privileges to POLICY_HOLDER...');
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON POLICYHOLDER TO POLICY_HOLDER';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON CLAIM TO POLICY_HOLDER';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON CLAIM_LOG TO POLICY_HOLDER';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON INSURANCE_APPLICATION TO POLICY_HOLDER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON PROVIDER TO POLICY_HOLDER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON PAYMENT TO POLICY_HOLDER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON POLICY TO POLICY_HOLDER';
    dbms_output.put_line('Privileges granted to POLICY_HOLDER.');

    -- Grant privileges to ADJUSTER
    dbms_output.put_line('Granting privileges to ADJUSTER...');
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON CLAIM TO ADJUSTER';
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON CLAIM_LOG TO ADJUSTER';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON CLAIM_LOG TO ADJUSTER';
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON PAYMENT TO ADJUSTER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON POLICYHOLDER TO ADJUSTER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON POLICY TO ADJUSTER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON AGENT TO ADJUSTER';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON PAYMENT TO ADJUSTER';
    dbms_output.put_line('Privileges granted to ADJUSTER...');

    -- Grant privileges to MANAGER
    dbms_output.put_line('Granting privileges to MANAGER...');
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON INSURANCE_APPLICATION TO MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON CLAIM TO MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON CLAIM_LOG TO MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT, UPDATE ON AGENT TO MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON POLICYHOLDER TO MANAGER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON POLICY TO MANAGER';
    dbms_output.put_line('Privileges granted to MANAGER.');

    -- Grant privileges to SALESMAN
    dbms_output.put_line('Granting privileges to SALESMAN...');
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON INSURANCE_APPLICATION TO SALESMAN';
    EXECUTE IMMEDIATE 'GRANT SELECT ON POLICYHOLDER TO SALESMAN';
    EXECUTE IMMEDIATE 'GRANT SELECT ON AGENT TO SALESMAN';
    dbms_output.put_line('Privileges granted to SALESMAN.');

EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line('An error occurred during granting privileges: ' || SQLERRM);
END;
/

COMMIT;
