SET SERVEROUTPUT ON;

DECLARE
    view_exists INTEGER;
BEGIN
    -- Grant privileges for Insurance_Application_Overview view
    BEGIN
        SELECT COUNT(*) INTO view_exists FROM USER_VIEWS WHERE VIEW_NAME = 'INSURANCE_APPLICATION_OVERVIEW';
        IF view_exists = 1 THEN
            EXECUTE IMMEDIATE 'GRANT SELECT ON INSURANCE_APPLICATION_OVERVIEW TO ICPS_CORE';
            EXECUTE IMMEDIATE 'GRANT SELECT ON INSURANCE_APPLICATION_OVERVIEW TO PROVIDER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON INSURANCE_APPLICATION_OVERVIEW TO SALESMAN';
            EXECUTE IMMEDIATE 'GRANT SELECT ON INSURANCE_APPLICATION_OVERVIEW TO MANAGER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON INSURANCE_APPLICATION_OVERVIEW TO ADJUSTER';
            DBMS_OUTPUT.PUT_LINE('Privileges granted on INSURANCE_APPLICATION_OVERVIEW');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error granting privileges on INSURANCE_APPLICATION_OVERVIEW: ' || SQLERRM);
    END;

    -- Grant privileges for Active_Policies_Summary view
    BEGIN
        SELECT COUNT(*) INTO view_exists FROM USER_VIEWS WHERE VIEW_NAME = 'ACTIVE_POLICIES_SUMMARY';
        IF view_exists = 1 THEN
            EXECUTE IMMEDIATE 'GRANT SELECT ON ACTIVE_POLICIES_SUMMARY TO ICPS_CORE';
            EXECUTE IMMEDIATE 'GRANT SELECT ON ACTIVE_POLICIES_SUMMARY TO PROVIDER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON ACTIVE_POLICIES_SUMMARY TO SALESMAN';
            EXECUTE IMMEDIATE 'GRANT SELECT ON ACTIVE_POLICIES_SUMMARY TO MANAGER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON ACTIVE_POLICIES_SUMMARY TO ADJUSTER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON ACTIVE_POLICIES_SUMMARY TO POLICY_HOLDER';
            DBMS_OUTPUT.PUT_LINE('Privileges granted on ACTIVE_POLICIES_SUMMARY');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error granting privileges on ACTIVE_POLICIES_SUMMARY: ' || SQLERRM);
    END;

    -- Grant privileges for Pending_Claims_Overview view
    BEGIN
        SELECT COUNT(*) INTO view_exists FROM USER_VIEWS WHERE VIEW_NAME = 'PENDING_CLAIMS_OVERVIEW';
        IF view_exists = 1 THEN
            EXECUTE IMMEDIATE 'GRANT SELECT ON PENDING_CLAIMS_OVERVIEW TO ADJUSTER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON PENDING_CLAIMS_OVERVIEW TO MANAGER';
            DBMS_OUTPUT.PUT_LINE('Privileges granted on PENDING_CLAIMS_OVERVIEW');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error granting privileges on PENDING_CLAIMS_OVERVIEW: ' || SQLERRM);
    END;

    -- Grant privileges for Monthly_Claims_Statistics view
    BEGIN
        SELECT COUNT(*) INTO view_exists FROM USER_VIEWS WHERE VIEW_NAME = 'MONTHLY_CLAIMS_STATISTICS';
        IF view_exists = 1 THEN
            EXECUTE IMMEDIATE 'GRANT SELECT ON MONTHLY_CLAIMS_STATISTICS TO ICPS_CORE';
            EXECUTE IMMEDIATE 'GRANT SELECT ON MONTHLY_CLAIMS_STATISTICS TO PROVIDER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON MONTHLY_CLAIMS_STATISTICS TO SALESMAN';
            EXECUTE IMMEDIATE 'GRANT SELECT ON MONTHLY_CLAIMS_STATISTICS TO MANAGER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON MONTHLY_CLAIMS_STATISTICS TO ADJUSTER';
            DBMS_OUTPUT.PUT_LINE('Privileges granted on MONTHLY_CLAIMS_STATISTICS');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error granting privileges on MONTHLY_CLAIMS_STATISTICS: ' || SQLERRM);
    END;

    -- Grant privileges for Policyholder_Claim_History view
    BEGIN
        SELECT COUNT(*) INTO view_exists FROM USER_VIEWS WHERE VIEW_NAME = 'POLICYHOLDER_CLAIM_HISTORY';
        IF view_exists = 1 THEN
            EXECUTE IMMEDIATE 'GRANT SELECT ON POLICYHOLDER_CLAIM_HISTORY TO ICPS_CORE';
            EXECUTE IMMEDIATE 'GRANT SELECT ON POLICYHOLDER_CLAIM_HISTORY TO PROVIDER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON POLICYHOLDER_CLAIM_HISTORY TO SALESMAN';
            EXECUTE IMMEDIATE 'GRANT SELECT ON POLICYHOLDER_CLAIM_HISTORY TO MANAGER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON POLICYHOLDER_CLAIM_HISTORY TO ADJUSTER';
            DBMS_OUTPUT.PUT_LINE('Privileges granted on POLICYHOLDER_CLAIM_HISTORY');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error granting privileges on POLICYHOLDER_CLAIM_HISTORY: ' || SQLERRM);
    END;

    -- Grant privileges for Policy_Expiration_Alert view
    BEGIN
        SELECT COUNT(*) INTO view_exists FROM USER_VIEWS WHERE VIEW_NAME = 'POLICY_EXPIRATION_ALERT';
        IF view_exists = 1 THEN
            EXECUTE IMMEDIATE 'GRANT SELECT ON POLICY_EXPIRATION_ALERT TO SALESMAN';
            DBMS_OUTPUT.PUT_LINE('Privileges granted on POLICY_EXPIRATION_ALERT');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error granting privileges on POLICY_EXPIRATION_ALERT: ' || SQLERRM);
    END;

    -- Grant privileges for Adjuster_Performance_Metrics view
    BEGIN
        SELECT COUNT(*) INTO view_exists FROM USER_VIEWS WHERE VIEW_NAME = 'ADJUSTER_PERFORMANCE_METRICS';
        IF view_exists = 1 THEN
            EXECUTE IMMEDIATE 'GRANT SELECT ON ADJUSTER_PERFORMANCE_METRICS TO MANAGER';
            DBMS_OUTPUT.PUT_LINE('Privileges granted on ADJUSTER_PERFORMANCE_METRICS');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error granting privileges on ADJUSTER_PERFORMANCE_METRICS: ' || SQLERRM);
    END;

    -- Grant privileges for Payment_Processing_Queue view
    BEGIN
        SELECT COUNT(*) INTO view_exists FROM USER_VIEWS WHERE VIEW_NAME = 'PAYMENT_PROCESSING_QUEUE';
        IF view_exists = 1 THEN
            EXECUTE IMMEDIATE 'GRANT SELECT ON PAYMENT_PROCESSING_QUEUE TO MANAGER';
            EXECUTE IMMEDIATE 'GRANT SELECT ON PAYMENT_PROCESSING_QUEUE TO ADJUSTER';
            DBMS_OUTPUT.PUT_LINE('Privileges granted on PAYMENT_PROCESSING_QUEUE');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error granting privileges on PAYMENT_PROCESSING_QUEUE: ' || SQLERRM);
    END;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An error occurred during view privilege assignment: ' || SQLERRM);
END;
/
